In [29]:
import pandas as pd
import re

In [30]:
fk = pd.read_csv("fake.csv")
tr = pd.read_csv("true.csv")

In [31]:
fk.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [45]:
fk = fk[['title']]
tr = tr[['title']]
fk['label'] = 0
tr['label'] = 1

df = pd.concat([fk,tr])

In [50]:
y = df.drop("label",axis=1,inplace = True)
df.head()

                                               title
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

In [66]:
type(df)

pandas.core.frame.DataFrame

In [53]:
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize,word_tokenize

In [67]:
df.isnull().sum()

title    0
dtype: int64

In [68]:
corpus = []
stem = PorterStemmer()
lem = WordNetLemmatizer()
for i in range(len(df)):
    words = str(df['title'][i]).lower()
    words = re.sub("[^0-9a-zA-z]"," ",words)
    
    # ans = [lem.lemmatize(word) for word in words if word not in stopwords.words('english')]
    # corpus.append(ans)

0     donald trump sends out embarrassing new year     0    as u s  budget fight looms  republicans flip t    name  title  dtype  object
1     drunk bragging trump staffer started russian     1    u s  military to accept transgender recruits o    name  title  dtype  object
2     sheriff david clarke becomes an internet joke    2    senior u s  republican senator   let mr  muell    name  title  dtype  object
3     trump is so obsessed he even has obama s name    3    fbi russia probe helped by australian diplomat    name  title  dtype  object
4     pope francis just called out donald trump dur    4    trump wants postal service to charge  much mor    name  title  dtype  object
5     racist alabama cops brutalize black boy while    5    white house  congress prepare for talks on spe    name  title  dtype  object
6     fresh off the golf course  trump lashes out a    6    trump says russia probe will be fair  but time    name  title  dtype  object
7     trump said some insanely racist stuff inside     7    factbox  trump on twitter  dec 29    approval     name  title  dtype  object
8     former cia director slams trump over un bully    8           trump on twitter  dec 28    global warming name  title  dtype  object
9     watch  brand new pro trump ad features so muc    9    alabama official to certify senator elect jone    name  title  dtype  object
10     papa john s founder retires  figures out raci    10    jones certified u s  senate winner despite moo    name  title  dtype  object
11     watch  paul ryan just told us he doesn t care    11    new york governor questions the constitutional    name  title  dtype  object
12     bad news for trump   mitch mcconnell says no     12    factbox  trump on twitter  dec 28    vanity fa    name  title  dtype  object
13     watch  lindsey graham trashes media for portr    13       trump on twitter  dec 27    trump  iraq  syria name  title  dtype  object
14     heiress to disney empire knows gop scammed us    14    man says he delivered manure to mnuchin to pro    name  title  dtype  object
15     tone deaf trump  congrats rep  scalise on los    15    virginia officials postpone lottery drawing to    name  title  dtype  object
16     the internet brutally mocks disney s new trum    16    u s  lawmakers question businessman at 2016 tr    name  title  dtype  object
17     mueller spokesman just f cked up donald trump    17    trump on twitter  dec 26    hillary clinton  t    name  title  dtype  object
18     snl hilariously mocks accused child molester     18    u s  appeals court rejects challenge to trump     name  title  dtype  object
19     republican senator gets dragged for going aft    19    treasury secretary mnuchin was sent gift wrapp    name  title  dtype  object
20     in a heartless rebuke to victims  trump invit    20    federal judge partially lifts trump s latest r    name  title  dtype  object
21     ky gop state rep  commits suicide over allega    21    exclusive  u s  memo weakens guidelines for pr    name  title  dtype  object
22     meghan mccain tweets the most amazing respons    22    trump travel ban should not apply to people wi    name  title  dtype  object
23     cnn calls it  a democrat will represent alaba    23    second court rejects trump bid to stop transge    name  title  dtype  object
24     white house  it wasn t sexist for trump to sl    24    failed vote to oust president shakes up peru s    name  title  dtype  object
25     despicable trump suggests female senator woul    25    trump signs tax  government spending bills int    name  title  dtype  object
26     accused child molesting senate candidate roy     26    companies have up to a year for new u s  tax b    name  title  dtype  object
27     watch  fox host calls for a  cleansing  of th    27    trump on twitter  dec 22    tax cut  missile d    name  title  dtype  object
28     liberal group trolls trump at roy moore rally    28    mexico to review need for tax changes after u     name  title  dtype  object
29     don jr  tries to mock al franken s resignatio    29    senate leader mcconnell sees a more collegial     name  title  dtype  object
30     breaking  cop finally gets his due  walter sc    30    alabama to certify democrat jones winner of se    name  title  dtype  object
31     watch  is this proof trump is unfit for service  31    mcconnell happier with trump tweets after tax     name  title  dtype  object
32     trump completely screws the middle east peace    32    house panel asks trump ex top aide bannon to t    name  title  dtype  object
33     trump only cares about trump  why he is recog    33    callista gingrich becomes trump s envoy to pop    name  title  dtype  object
34     watch  trump supporting coal ceo upset trump     34    as republicans aim to ride economy to election    name  title  dtype  object
35     sitting gop senator has had enough  donates t    35    exclusive  state department tells refugee agen    name  title  dtype  object
36     republican national committee  better a pedop    36    congress votes to avert shutdown  sends trump     name  title  dtype  object
37     donald trump s eating habits could be dramati    37    factbox  big ticket items at center of congres    name  title  dtype  object
38     john mccain wanted another 74 twitter followe    38    in victory for trump  judge tosses suit on for    name  title  dtype  object
39     this sarah huckabee sanders tweet about attac    39    senate shelves disaster aid bill until next month name  title  dtype  object
40     fbi agents destroy donald trump after he atta    40     trump on twitter  dec 21    tax cuts  home sales name  title  dtype  object
41      ghost of witness flipped   hilarious snl ski    41    house widens ethics probe to include farenthol    name  title  dtype  object
42     leaked email proves trump officials aware rus    42    u s  court rejects trump bid to stop transgend    name  title  dtype  object
43     trump just admitted he knew flynn lied to the    43     u s  house approves  81 billion for disaster aid name  title  dtype  object
44     watch this awesome mashup of michael flynn le    44    house democrats rally to protect special couns    name  title  dtype  object
45     white house panics knowing flynn is going to     45    second u s  judge blocks trump administration     name  title  dtype  object
46     breaking  michael flynn cracks   will testify    46    senators seek to stop expansion of airport fac    name  title  dtype  object
47     trump gets an epic f  ck you from britain ove    47    u s  launches effort to reduce reliance on imp    name  title  dtype  object
48     this hilarious campaign ad shows voters how t    48    short term government funding  disaster aid bi    name  title  dtype  object
49     joe scarborough  it s not our imagination   t    49    spy chiefs pressure congress to renew expiring    name  title  dtype  object
50     sources confirm robert mueller s office inter    50    trump urges congress to pass short term spendi    name  title  dtype  object
51     trump sends crazy time tweet to the wrong acc    51    house gives final approval to tax bill  delive    name  title  dtype  object
52     americans once elected a president after he w    52       u s  tax plan roils popular bet in bond market name  title  dtype  object
53     trump s biggest kkk fan is back  and he just     53    u s  lawmakers seek temporary extension to int    name  title  dtype  object
54     trump spent the night retweeting a white supr    54    trump commutes fraud sentence of kosher meatpa    name  title  dtype  object
55     sean hannity is throwing a stage 4 temper tan    55    u s  responds in court fight over illegal indo    name  title  dtype  object
56     democrats give trump a big f  ck you after he    56        democrat franken to leave senate on january 2 name  title  dtype  object
57     trump wakes up to scream at black people afte    57    u s  lawmakers seek temporarily extension to i    name  title  dtype  object
58     trump supporters object to prince harry s rec    58    top democrat says trump firing of mueller coul    name  title  dtype  object
59     while honoring native american code talkers      59    u s  tax bill may face lawsuits with long odds    name  title  dtype  object
60     pro trump group is now using pictures of an o    60    vote in senate on  dreamers  hinges on biparti    name  title  dtype  object
61     breitbart editor to cnn host  a song by ringo    61    white house says tax bill will not hurt puerto    name  title  dtype  object
62     former obama photographer takes trolling trum    62    democrats plan to use tax bill to attack repub    name  title  dtype  object
63     just back from a golfing vacay  trump says he    63    after ruling  virginia legislature s majority     name  title  dtype  object
64     two weeks before election  trump still defend    64    fight over alaska arctic drilling has just beg    name  title  dtype  object
65     principles over power  why republicans need t    65    senator cornyn trying to get big corn behind u    name  title  dtype  object
66     trump  everything you heard me say on the acc    66    in georgia  battle of the  staceys  tests demo    name  title  dtype  object
67     cnn blisters trump after he attacks them for     67    democrat wins by one vote in virginia legislat    name  title  dtype  object
68     sean hannity gets wrecked for yelling at time    68    fbi deputy director to sit for closed intervie    name  title  dtype  object
69     time magazine humiliates trump after he lies     69    white house expects congress to waive spending    name  title  dtype  object
70     ivanka defends malia obama from attacks  her     70                 trump on twitter  dec 20    tax bill name  title  dtype  object
71     trumpsters launch insane conspiracy theory ab    71              what s in the final republican tax bill name  title  dtype  object
72     gay gop operative endorses doug jones over  b    72    trump  market has not fully digested tax cut c    name  title  dtype  object
73     watch  retired alabama cop  we were told to k    73    white house aide sees temporary funding fix fo    name  title  dtype  object
74     new york times reports there s an actual russ    74    tax bill s  pass through  rule will aid wealth    name  title  dtype  object
75     fox news bans gene simmons for life for haras    75    u s  tax cuts won t make housing more affordab    name  title  dtype  object
76     watch  nicolle wallace takes trump to the woo    76    banks  healthcare service firms among winners     name  title  dtype  object
77     pastor goes full y all qaeda defending roy mo    77    trump s supreme court appointee gorsuch plots     name  title  dtype  object
78     trump s national security adviser reportedly     78    republicans seek to question fbi officials in     name  title  dtype  object
79     trump s favorite news channel tries to soothe    79    trump aides hope win on taxes will stem slide     name  title  dtype  object
80     texas governor just broke with trump  this is    80    congress faces tricky path to avoid government    name  title  dtype  object
81     conservative  christian  leader kept a sexual    81    factbox   big ticket items at center of congre    name  title  dtype  object
82     gop senator caught on hot mic trashing his ow    82    senate parliamentarian rules against tax bill     name  title  dtype  object
83     donald trump is destroying the country s repu    83    senate panel snubs trump s pick to run exim  o    name  title  dtype  object
84     trump just got his p ssy handed to him by new    84    house will likely need to vote again on tax bi    name  title  dtype  object
85     chaos ensues after man accidentally shoots hi    85    instant view  house approves biggest tax overh    name  title  dtype  object
86     new accuser confirms she got roy moore banned    86    senate begins debate on final republican tax bill name  title  dtype  object
87     roy moore is asking people to snitch on the m    87    bill could make congress members liable for ha    name  title  dtype  object
88     trump admin  tosses out another obama rule       88    green groups sue trump administration over del    name  title  dtype  object
89     the internet lights up after the pentagon acc    89    house democratic leaders urging  no  vote on s    name  title  dtype  object
90     anti gay gop rep gets busted for having inapp    90    pence to preside over senate tax bill vote  hi    name  title  dtype  object
91     that time trump mocked marco rubio for drinki    91    senate to vote on final tax bill tuesday eveni    name  title  dtype  object
92     watch  corporate ceos shock trump s economic     92    republicans appear all but certain to pass tax    name  title  dtype  object
93     texas sheriff threatens to jail truck owner f    93    court orders trump administration to give immi    name  title  dtype  object
94     watch  delusional trump fans lash out at fox     94    house plan would increase trump s disaster aid    name  title  dtype  object
95     roy moore supporting republican loses it afte    95    house panel chair introduces  81 billion disas    name  title  dtype  object
96     that story trump just told the press about ob    96    trump nominates liberty university professor t    name  title  dtype  object
97     this 4 year old tweet from donald trump shows    97    trump on twitter  dec 18    congressional race    name  title  dtype  object
98     oops  trump judicial nominee didn t tell cong    98    trump cabinet officials to visit puerto rico t    name  title  dtype  object
99     trump laughs after philippine leader calls jo    99     dreamer  immigration bill not on u s  senate     name  title  dtype  object
100     watch  joe biden just wrecked trump in six wo    100    senator warren hits out at  effort to politici    name  title  dtype  object
101     busted  leaked documents prove trump took lau    101    trump strategy document says russia meddles in    name  title  dtype  object
102     perverted gop state rep  corners lobbyist  tr    102    republican senator collins says she will vote     name  title  dtype  object
103     all of roy moore s former colleagues knew he     103    democratic u s  senator seeks audit of epa chi    name  title  dtype  object
104     watch  christian right founder condemns them     104    republican senator lee says he will vote for t    name  title  dtype  object
105     conservative  christian  leader defends pedop    105    trump  u s  has  no choice  but to deal with n    name  title  dtype  object
106     trump throws intelligence community under the    106    trump judicial nominee withdraws from consider    name  title  dtype  object
107     this old mike pence tweet sure is uncomfortab    107    trump calls for u s  infrastructure plan after    name  title  dtype  object
108     sean hannity just said child molestation is o    108    final republican tax bill slashes u s  corpora    name  title  dtype  object
109     newsweek just made their best cover ever and     109    factbox  what s in the final u s  republican t    name  title  dtype  object
110     alabama republican just defended pedophilia u    110    trump defends tax plan as  great christmas gif    name  title  dtype  object
111     gop senate candidate turns out to be a disgus    111    house to vote on tax bill tuesday afternoon  a    name  title  dtype  object
112     senate democrats have been sneaking around be    112    white house optimistic congress will avoid gov    name  title  dtype  object
113     sunday s massacre in texas bumped columbine o    113    u s  taxpayers rush to claim deductions under     name  title  dtype  object
114     sean hannity barely spends 6 seconds on last     114    republicans confident tax bill to become law t    name  title  dtype  object
115     maine voters tell trump to go f ck himself  e    115    republican senator john mccain leaves washingt    name  title  dtype  object
116     watch  rick santorum torches trump for not ta    116    trump says not considering firing u s  special    name  title  dtype  object
117     trump seething after humiliating virginia ele    117    trump allies say mueller unlawfully obtained t    name  title  dtype  object
118     the resistance just gave trump a huge f  ck y    118    senator elect jones not joining calls for trum    name  title  dtype  object
119     trump s justice dept  realizes prosecuting wo    119    trump administration bans selected words at he    name  title  dtype  object
120     trump jr  goes full dumba   on twitter by pro    120    congressman will not seek relection amid misco    name  title  dtype  object
121     trump just openly called for a third world wa    121    trump to say in security speech that china is     name  title  dtype  object
122     oops  trump agrees that people like him shoul    122    factbox  trump on twitter  december 15    quan    name  title  dtype  object
123     miss texas gave a very unexpected answer when    123    republican tax bill retains u s  electric vehi    name  title  dtype  object
124     trump is trying to make facebook give him per    124    attorney general sessions has lukewarm praise     name  title  dtype  object
125     multiple witnesses confirm  the pee pee tapes    125    senate democrats to force vote on fcc net neut    name  title  dtype  object
126     fox news just completed transformation into s    126    u s  lawmaker probed on sex reports  second co    name  title  dtype  object
127     trump tells japanese diplomats he never knew     127    republicans join push to lift secrecy around m    name  title  dtype  object
128     latest from conservatives  god was answering     128    trump officials brief hill staff on saudi reac    name  title  dtype  object
129     university of texas police kick humiliated na    129    u s  judge to lift house arrest for former tru    name  title  dtype  object
130     russian lawyer drops bomb on donald trump jr     130    republican senator corker says he will support    name  title  dtype  object
131     watch  republican lawmaker claims forcing wom    131    rubio signals support for tax bill after child    name  title  dtype  object
132     someone tried to cash in on antifa with these    132    u s  tax negotiators raising refundable portio    name  title  dtype  object
133     senator delivers scathing rebuke to his gop c    133    republicans have finalized compromise u s  tax    name  title  dtype  object
134     a reminder of how much the nra has spent on t    134    republican senator rubio will back tax bill  c    name  title  dtype  object
135     27 people murdered in texas mass shooting  an    135    exclusive  senator cruz wants to cap renewable    name  title  dtype  object
136     trump went to japan and immediately proved he    136    trump administration issues new rules on u s      name  title  dtype  object
137     the walls close in on trump as his disgraced     137     trump urges moore to concede alabama senate race name  title  dtype  object
138     former watergate prosecutor  mueller could ga    138    net neutrality repeal gives democrats fresh wa    name  title  dtype  object
139     gop lawmaker links abortion to the economy in    139    as republican tax vote nears  more senators waver name  title  dtype  object
140     hawaiians had the perfect signs to infuriate     140    factbox  trump on twitter  december 14    stoc    name  title  dtype  object
141     trump wants the supreme court to punish lawye    141    house committee questions head of trump campai    name  title  dtype  object
142     hypocrite ivanka trump humiliated for calling    142    republican governors meet with pence over naft    name  title  dtype  object

KeyError: 23481

In [76]:
df['title'][23480]

'10 U.S. Navy Sailors Held by Iranian Military – Signs of a Neocon Political Stunt'

In [74]:
df.shape

(44898, 1)