In [53]:
import pandas as pd
import re

In [54]:
fk = pd.read_csv("fake.csv")
tr = pd.read_csv("true.csv")

In [55]:
fk.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [56]:
fk = fk[['title']]
tr = tr[['title']]
fk['label'] = 0
tr['label'] = 1

df = pd.concat([fk,tr])

In [57]:
df = df.sample(frac=1).reset_index(drop=True)

In [58]:
y = df.pop('label')
# df.drop("label",axis=1,inplace = True)
df.head()

                                               title
0  Swiss woman abducted in Sudan by criminal gang...
1  U.N. brings Syria talks under one roof, not ye...
2  OBAMA’S GUN-RUNNING, Lying, Race-Baiting AG Is...
3   SICKENING: Donald Trump Actually Hit On A 10-...
4  (VIDEO) AMAZING! TED CRUZ GETS CODE PINK TO SH...

In [59]:
type(df)

pandas.core.frame.DataFrame

In [60]:
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize,word_tokenize

In [61]:
df.isnull().sum()

title    0
dtype: int64

In [62]:
corpus = []
stem = PorterStemmer()
lem = WordNetLemmatizer()
for i in range(len(df)):
    words = str(df['title'][i]).lower()
    words = re.sub('[^a-zA-Z]',' ',words)
    words = words.split()
    ans = [stem.stem(word) for word in words if word not in stopwords.words('english')]
    ans = ' '.join(ans)
    corpus.append(ans)

In [63]:
# corpus = []
# h = "Boston Globe denounces Trump candidacy in 'front page' satire "
# words = h.lower()
# words = re.sub('[^a-zA-Z]',' ',words)   
# words = words.split()
# ans = [stem.stem(word) for word in words if word not in stopwords.words('english')]
# ans = ' '.join(ans)
# corpus.append(ans)

In [64]:
corpus

['swiss woman abduct sudan crimin gang ransom offici',
 'u n bring syria talk one roof yet one room',
 'obama gun run lie race bait ag back never guess whose job reportedli hope take video',
 'sicken donald trump actual hit year old girl video',
 'video amaz ted cruz get code pink shut listen iran nuke deal',
 'mike penc cancel anoth trump event campaign implod imag',
 'bannon role trump administr set critic firestorm',
 'virginia lawmak reach bipartisan deal gun issu',
 'iraqi pm offic say turkey agre deal baghdad oil export',
 'uk polic alert suspect packag london islington area',
 'watch reagan warn us draw battl line trump finish battl liber fascist video',
 'chuck schumer republican real problem trump behind close door video',
 'robert parri sort russia mess',
 'trump give slap press flynn guilti plea leav white hous video',
 'watch cheroke peopl express disgust lie elizabeth warren fake nativ american heritag get prestigi law professor job',
 'u homeland secretari kelli warn guatemalan stay home',
 'obama made christian pastor pay ticket home iran got secret billion ransom releas',
 'video leftist cnn anchor tell racist us rep baltimoreriot vet fault come back war readi battl',
 'hungari badass prime minist respond threat eu respons make everyon want stand cheer video',
 'view loudmouth liber joy behar call bill clinton rape victim tramp show target women video',
 'cnn liber anchor freak navi seal ask truth believ reaction video',
 'chumle pawn star arrest la vega feloni charg video',
 'germani schaeubl press ecb unwind loos monetari polici',
 'teen vogu school major news network show know trump',
 'trump twitter dec tax bill',
 'trump talk terror attack happen oversea last night one littl problem',
 'trump trade advis say hope reach trade deal south korea',
 'n korea reveal plan unleash unimagin attack could lead electron armageddon',
 'marklevin freak awesom obama negoti iran iranian gener say israel destruct negoti',
 'north korea threat loom trump address world leader u n',
 'health insur quietli shape obamacar replac fewer risk',
 'alec baldwin tore trump apart limb stupid limb hellish weekend tyranni tweet',
 'rush finish obama slap billion regul america exit',
 'watch snl church ladi return hilari mock ted cruz donald trump',
 'thai univers remov student leader defi royalist tradit',
 'watch dinesh souza great comeback student call hack video',
 'obama blood hand otto warmbier die day releas north korean captiv video',
 'break liber media worst nightmar come true kellyann conway land top posit trump team',
 'trump tap anti iran deal congressman head cia left goe ballist',
 'texa lawmak file crucial bill could save countless live video',
 'suprem court decis lead justic ginsburg deliv blow big busi',
 'mark steyn hammer democrat climat chang scam effect enforc state ideolog',
 'get campu univers plan weed conserv professor hire liber educ',
 'fox news roger ail actual harass femal journalist decad',
 'catalonia urg eu intervent independ vote disput',
 'hillari clinton presid alreadi begun lame duck promot war syria',
 'al sharpton blame racism trump victori say gonna blame anyon video',
 'britain becom u vassal state say french presidenti hope macron',
 'syrian refuge famili lie bed bug infest get better hous',
 'u court rule trump travel ban come wednesday',
 'stephen colbert gave us futurist view trump presid far video',
 'watch anti american actress emili blunt dixi chick day new movi releas video',
 'stun vintag video show barack obama mock god bibl year ago',
 'philippin say polici trump popular dutert rate dip',
 'trump meet senat ernst amid vice presidenti specul',
 'china hope side word action reduc tension korean peninsula',
 'betsi devo total humili keynot speech histor black univers',
 'hundr afghan demonstr offens u leaflet',
 'watch senat john mccain tell tmz sport report okay nfl player disrespect flag',
 'fbi agent indict kill lavoy finicum hire high profil dc lawyer',
 'tea parti republican huelskamp lose elect bid u hous',
 'boiler room quantum swamp chess',
 'john boehner tri post facebook like regular guy fail miser pay dearli imag',
 'china back u n call justic yemen u saudi',
 'american liar wingnut icon chri kyle hero made',
 'uk princ harri say troop need mental well physic fit combat train',
 'stun develop obama give million us tax dollar mexico build border wall',
 'ha believ hillari luxuri scoobi van',
 'wow hous intellig chair confirm trump correct trump transit team surveil obama video',
 'wow pro castro leftist cuban fled castro escap annoy wife famili video',
 'bill reilli said women prove certifi hole video',
 'blow trump u appeal court refus reinstat travel ban',
 'desper trump doubl wiretap lie say proven right',
 'hillari final make statement sexual predat mega democrat donor harvey weinstein get destroy bill clinton rape accus',
 'trump nomin quarl fed top bank regul',
 'trump claim done isi obama scorecard say lie',
 'obama feder polic forc baltimor mayor call bold polic reform doj investig',
 'even donald trump inaugur poster glare misspel imag',
 'right wing mom beat kid bloodi pulp lead god video',
 'texa governor vp abbott push back obama agenda like one els video',
 'scotland sturgeon seek assur brexit transit',
 'video rino strategist karl rove solut gun violenc repeal second amend',
 'u gulf nation target yemen terror financ',
 'yr old state get state fund sex chang oper without parent consent need consent use tan bed',
 'break charg polic offic shoot death keithscott ex con muslim beat wife kid previous shot cop',
 'tillerson say back full review iran nuclear deal',
 'martha stewart make lewd gestur toward trump portrait art fair boycott',
 'ukrain say hope continu support russia u trump',
 'donald trump jr wreck fake indian elizabeth warren twitter conserv cheer',
 'listen laugh undercov video captur diabol remark nation abort feder confer eyebal fell lap gross',
 'major republican celebr turn trump fan shock tweet',
 'yemen hadi see militari solut crisi arabiya tv',
 'turkey issu detent order soldier gulen link anadolu',
 'trump son plug father presid hotel chain morn tv perfectli legal',
 'newsflash imperi presid state refus iran deal video',
 'democrat trump wall lawbreak wall keep berni sander fan',
 'watch chri cuomo shred kellyann conway hypocrit defend trump pay play scheme',
 'trump back golfer make master fold shirt give lesson',
 'sander say lay hundr campaign worker ny time',
 'trump staff writer take respons melania speech controversi',
 'trump nomin callista gingrich ambassador vatican',
 'florida cite complaint chevron ga price shortag mount',
 'u call pakistan arrest recent freed islamist leader',
 'trump urg senat republican move ahead healthcar reform',
 'italian parliament vote toughen law fascist propaganda',
 'cnnblackmail trend network blackmail trump meme reddit user',
 'illinoi fight potenti hike disabl care fund',
 'republican presidenti candid cruz make announc p',
 'immigr case could hurt republican outreach u hispan',
 'cuban brutal attack brave man wave us flag front communist parad video',
 'amid opposit trump make low budget request mexico border wall',
 'iran say resign lebanes pm creat tension region',
 'tucker tri reason crazi feminist insert gender polit onto newborn care video',
 'face book side muslim jihadist free speech muham cartoon contest winner remov social media site',
 'u hous pass bill requir warrant search old email',
 'robert f kennedi son announc run illinoi governor',
 'trump administr declin name china currenc manipul',
 'britain may parti leader agre tackl sexual harass new measur',
 'donald rumseld humili view dingbat joy behar call understand presid elect video',
 'fox news ask man pictur new york solidar march respons priceless',
 'key u hous democrat push expand russia probe',
 'take pay huge fine nfl allow player honor victim memori cleat disrespect flag okay',
 'us coalit airstrik syrian armi al tanf anoth calcul war crime aim destroy arab uniti',
 'watch fox attack sander say rich kid deserv free colleg parent work hard',
 'debat stifl cambodia crackdown spread fear',
 'trump back new york bours battl saudi aramco list',
 'trump come swing watch announc tax regul leader mean busi video',
 'wow american stun mom caught video encourag young child help gang thug destroy polic car st loui',
 'cher attack trump compar bill clinton infidel trump marriag forget one import fact',
 'cuba hold municip elect road castro era end',
 'mcconnel say plan vote obamacar repeal amend',
 'trump deni tillerson threaten resign twitter',
 'michigan republican pass bill would put gay straight coupl prison',
 'conserv freak see obama front che guevara mural tweet',
 'trump doubl law order appeal white hous bid',
 'mind blow interact map show muslim refuge come go',
 'white hous defend statement audienc trump inaugur',
 'tehran tom cotton say u justic system anglo american jail enough',
 'trump humili approv rate even lower clinton sex scandal',
 'watch hypocrit mike penc call democrat obstruct trump suprem court nomine unpreced',
 'foursom trump play golf great video',
 'obama respons year old girl flint give us hope video',
 'trump oppon urg u suprem court rule travel ban',
 'watch ted cruz insult everyon debat stage surpris reason video',
 'u envoy haley russia interfer elect warfar',
 'boiler room ep deeper game master chao strike',
 'shot fire dmz north korean soldier defect south',
 'presid obama arriv cuba',
 'senat grill u educ secretari propos slash budget',
 'u n trump tough talk open door macron diplomaci',
 'clinton fli zone syria save live lead war russia',
 'la time columnist slam mock sarah sander sexist articl cartoon',
 'marco rubio slam gop obstruct obama surpris speech senat floor video',
 'trump demand investig polit enemi get torn apart twitter tweet',
 'u court put obamacar case hold trump take offic',
 'democrat conveni forget prison obama pardon includ crack dealer commit horrif crime innoc american',
 'exclus republican could target obamacar tax wider tax overhaul bradi',
 'michael flynn resign letter omit one crucial fact also kiss trump orang ass',
 'hilari polit cartoon mock trump perfectli alleg sacrific',
 'senat bank chair democrat say still hope deal dodd frank bank rule rewrit',
 'transcript reuter interview epa administr scott pruitt',
 'trump say ye feder fund plan parenthood one condit gonna love',
 'russia expect de mistura visit moscow ria',
 'ambassador john bolton susan rice real legal problem video',
 'court case travel ban execut order',
 'shock ad show trump racist campaign ruin children live video',
 'hillari clinton kkk smear trump democrat strategi',
 'senat warren endors clinton presid',
 'u hous republican weaken ethic bodi return congress',
 'twitter destroy trump use dwyan wade person tragedi pander black vote',
 'u justic weigh feder fraud claim woman death',
 'recov sever malnutrit yemen',
 'mexico urg respect u presidenti elect',
 'five crew miss dredger collid tanker singapor',
 'amnesti urg independ probe atroc bomb battl philippin marawi citi',
 'roy moor accus admit forg yearbook',
 'someth truli extraordinari refresh happen cnn democrat debat video',
 'break presid trump make pick suprem court',
 'u withdraw pari deal good sign aviat accord iata',
 'famili lost argentina submarin crew decri govern respons',
 'muslim clock boy invent anyth move middl east attend prestigi program innov',
 'trump superstar attorney trump u case huge hillari clinton backer',
 'trump answer one question could sink campaign conserv video',
 'charl barkley say anyon critic obama racist gay right import religi freedom america video',
 'sunday screen counter intellig compani',
 'break email leak berni need ground pulp crush hard',
 'boom new poll number show clown news network fail destroy trump',
 'fire furi trump team talk north korea congress',
 'pressur trump price resign health secretari privat plane uproar',
 'hillari support launch vile attack woman hillari threaten come forward rape alleg bill clinton hillari beat silenc liar',
 'austrian social democrat poll suggest late boost sourc newspap',
 'dubiou report advertis seek trump protest get paid fight trump',
 'protest call porto court agre woman adulteri factor attack',
 'berni sander white know like poor live ghetto video',
 'report presid trump replac sean spicer fox news person',
 'america primal scream david ick explain reason trump elect result',
 'watch gop rep dave brat turn tabl fakenew cnn accus collus liber media cnn action uneth illeg',
 'show sunday wire eye matrix acr hesher shawn helton',
 'break presid trump make nation secur advis pick great leader great strateg thinker video',
 'best meltdown tucker carlson blast senior writer newsweek trump mental hospit answer question video',
 'iraq warn kurdistan shut kirkuk oil flow',
 'trump ad assassin list presidenti promis',
 'ladi view hammer trump obviou racism gloriou video',
 'trump vietnam presid underscor free open access south china sea',
 'malaysia talk u firm ocean infin resum mh search',
 'obama make first visit u mosqu next week',
 'disast capitalist bill hillari clinton foundat use relief donat like atm',
 'showboat democrat walk moment silenc texa massacr victim screw nra',
 'trump visit britain could happen around june london polic chief',
 'republican parti chairman confid cleveland convent secur',
 'trump advis cohn remain talk swirl white hous departur',
 'u student rape alleg italian polic basi minist say',
 'u envoy russia visa consult consul may resum soon tass',
 'cuba tell u suspens visa hurt famili',
 'tennesse gop lawmak offer fund bundi terrorist arm insurg screenshot',
 'senat want answer miss tsa badg tsa tri block investig',
 'thoma sowel final column mani school produc artifici stupid',
 'watch hispan parent make shock video teach yr old say kill donald trump',
 'break tomi lahren suspend blaze make shock announc view video',
 'video lie lie lie state depart speak fork tongu rise radic islam',
 'berni sander flip dem anti berni dnc chair chosen',
 'hungari pm warn erod free movement eu citizen',
 'dog lover putin get top breed pup gift turkmen leader',
 'queen elizabeth prais british spirit christma address attack fire',
 'video detroit woman kill best friend presidenti race argument media refus say killer support obama',
 'kushner statement say collud foreign govern',
 'trump team incompet even book hotel room g summit',
 'anti trump radic taunt trump support isi flag photo behead video',
 'hollywood secret conserv club shut actor stop fight trump',
 'twitter destroy trump whine eric sell access administr tweet',
 'gop make america sick plan releas wors thought detail',
 'trump threaten cut aid u n member jerusalem vote',
 'u partner bloodsh jerusalem move erdogan say',
 'clinton get sander endors show parti uniti',
 'kushner met special counsel mueller russia probe cnn',
 'clinton foundat bar foreign corpor fund hillari clinton elect presid',
 'block protest block ice van remov illeg felon possibl deport video',
 'trump shove fellow nato leader asid first summit',
 'bridgewat execut mccormick declin defens depart role',
 'trump disclosur uk may say continu share intel u',
 'total cost taxpay mooch european vacat sicken',
 'paul ryan republican toler democrat disrupt hous',
 'break watch live feed freedom speech ralli ii front phoenix mosqu',
 'madelein albright regist muslim solidar',
 'shock video congressman caught meltdown threaten report video',
 'ireland say ongo failur northern ireland talk deepli concern',
 'boiler room ep establish hitmen media hack',
 'illinoi fix unpaid bill may end financi time bomb',
 'russian submarin fire cruis missil islam state syria',
 'trump strike blow iran nuclear deal major u polici shift',
 'transport secretari unequ distribut sidewalk keep poor shot american dream',
 'trump consid retir gener petraeu top diplomat bloomberg',
 'sarah sander hyster respons news cnn staffer boycot white hous christma parti',
 'watch fox host whine fair men condescend women',
 'wmd fraud sex un chemic weapon report syria contriv trigger sanction intervent',
 'exclus major american want congress move healthcar reform reuter ipso poll',
 'multi stage cyber attack net north korea million virtual currenc research',
 'meet trump japan abe end trump offici',
 'spain socialist leader agre rajoy launch constitut reform',
 'law say donald trump alreadi impeach might plan',
 'give em hell jess democrat start focus win instead whine video',
 'senat set begin debat puerto rico debt relief bill',
 'senat mike lee nail senat oppos suprem court nomine video',
 'factbox key figur zimbabw first ladi grace mugab g faction',
 'hyundai motor kia temporarili shut u plant due irma',
 'u n ban four ship north korea coal u delay four',
 'clinton book say trump debat stalk made skin crawl',
 'one palestinian christian muslim unit trump jerusalem call',
 'donald trump email scandal actual broke law jail',
 'man actual wrote art deal give trump tast medicin tweet',
 'delay republican congress prepar introduc tax bill',
 'boom navi seal vet destroy whini organ veteran trump video',
 'senat republican may repeal obamacar mandat tax bill cornyn',
 'watch dumb ss trump support bewild cnn host delus illeg voter',
 'break report clinton two aid broke nation secur law',
 'german admit sell gun munich attack shooter',
 'highlight trump presid januari pm est gmt',
 'berni sander receiv crucial nevada endors',
 'trump eye suprem court appeal court reject travel ban',
 'school infrastructur bond measur fill u ballot',
 'end fox news monopoli liber murdoch son fire bill reilli roger ail suspend eric boll get seriou competit',
 'u govern delay obama earn strip rule deadlin',
 'china say futil use trial taiwanes activist attack chines law',
 'debat disast hillari room full democrat undecid voter pa bar turn trump',
 'trump opt keep pentagon top offic anoth term',
 'south sudan rebel accus armi attack peac talk restart',
 'gop congresswoman destroy poll repeal obamacar tweet',
 'trump say discuss militari issu qatar kuwait emir',
 'trump spokeswoman humili tri make democrat look stupid tweet',
 'famili flee syria raqqa say air strike bring heavi toll',
 'nbc manag protect sh detail marri matt lauer disgust act sexual harass reveal democrat fan boy fire',
 'presid trump cuba send back escap cop killer poster child black live matter movement video',
 'citi decid allow illeg vote local elect',
 'muslim brotherhood peddl sharia social justic reason terrorist organ',
 'critic slam propos south carolina transgend bathroom bill',
 'senat tee account act regul fight intensifi',
 'muslim athlet given hero welcom arrest sexual abus yr old girl senat schumer help get around u visa denial',
 'democrat thug vandal republican offic across sever state deplor',
 'promin democrat claim old white leftist male wait wing hillari fall',
 'white hous scrap agenc paperwork rule push effici',
 'session panic cancel public testimoni want answer question russia',
 'sander reject deal puerto rico offer altern',
 'googl support u effort disclos buyer onlin polit ad',
 'spain see russian interfer catalonia separatist vote',
 'ted nugent insult women everywher disgustingli list men prefer gun imag',
 'jew around world alarm far right breakthrough germani',
 'rocker john kerri make outrag statement caus terror',
 'atzmon keep american dark',
 'trump call fledgl dictat congratul expand power',
 'mi school send welcom back packet warn kid wear u flag school',
 'russia threaten brand u sponsor radio liberti foreign agent',
 'china graft watchdog warn offici conceal extravag',
 'pro life scott walker sign two bill increas need abort',
 'watch sexist breitbart editor get hand abc report',
 'malaysia talk u firm ocean infin resum mh search',
 'nc gop rep make outrag racist statement respons charlott protest video',
 'obama epic win vs ebola media never told imag',

In [65]:


from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Dense,Bidirectional,Embedding
from tensorflow.keras.models import Sequential

In [66]:
voc_size = 10000
onehot = [one_hot(words,voc_size) for words in corpus]

In [73]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [76]:
ma = 0
for i in onehot:
    ma = max(ma,len(i))

In [77]:
ma

35

In [78]:
max_seq = 35

In [79]:
padded = pad_sequences(onehot,maxlen=max_seq,padding = 'pre')

In [80]:
padded

array([[   0,    0,    0, ..., 5705, 5528, 9789],
       [   0,    0,    0, ..., 4203, 6224, 3937],
       [   0,    0,    0, ..., 8724, 6984, 5948],
       ...,
       [   0,    0,    0, ..., 2456, 8799, 4174],
       [   0,    0,    0, ..., 3026, 1992, 5948],
       [   0,    0,    0, ..., 9015, 8706, 4478]])

In [81]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded, y, test_size=0.25, random_state=42)

In [86]:
from tensorflow.keras.layers import LSTM
model = Sequential()
model.add(Embedding(voc_size,35,input_length = 35))
model.add(LSTM(100))
# model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [87]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [89]:
model.fit(x_train,y_train,epochs=5,batch_size=32)

Epoch 1/5

1053/1053 ━━━━━━━━━━━━━━━━━━━━ 45s 42ms/step - accuracy: 0.9675 - loss: 0.0869
Epoch 2/5
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 39s 37ms/step - accuracy: 0.9800 - loss: 0.0564
Epoch 3/5
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 46s 44ms/step - accuracy: 0.9866 - loss: 0.0392
Epoch 4/5
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 43s 41ms/step - accuracy: 0.9899 - loss: 0.0287
Epoch 5/5
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 37s 35ms/step - accuracy: 0.9930 - loss: 0.0215

In [90]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 35, 35)         │       350,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 100)            │        54,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,213,505 (4.63 MB)

 Trainable params: 404,501 (1.54 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 809,004 (3.09 MB)

In [97]:
from sklearn.metrics import accuracy_score,confusion_matrix
pred = model.predict(x_test)
pred_binary = (pred > 0.5).astype(int).reshape(-1)  # Convert probabilities to binary labels
acc = accuracy_score(y_test, pred_binary)
conf = confusion_matrix(y_test, pred_binary)

351/351 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step

In [98]:
acc

0.9472605790645879

In [99]:
conf

array([[5568,  258],
       [ 334, 5065]], dtype=int64)