In [1]:
import pandas as pd
import re

In [2]:
fk = pd.read_csv("fake.csv")
tr = pd.read_csv("true.csv")

In [3]:
fk.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
fk = fk[['title']]
tr = tr[['title']]
fk['label'] = 0
tr['label'] = 1

df = pd.concat([fk,tr])

In [10]:
df = df.sample(frac=1).reset_index(drop=True)

In [12]:

y = df.drop("label",axis=1,inplace = True)
df.head()

                                               title
0  Boston Globe denounces Trump candidacy in 'fro...
1  Egypt detains 29 people on suspicion of espion...
2   House Intelligence Committee: Trump Lied Abou...
3  Buckeye targets normal operations at Bahamas o...
4  Suspected Boko Haram suicide bombers kill at l...

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize,word_tokenize

In [13]:
df.isnull().sum()

title    0
dtype: int64

In [34]:
corpus = []
stem = PorterStemmer()
lem = WordNetLemmatizer()
for i in range(len(df)):
    words = str(df['title'][i]).lower()
    words = re.sub('[^a-zA-Z]',' ',words)
    words = words.split()
    ans = [stem.stem(word) for word in words if word not in stopwords.words('english')]
    ans = ' '.join(ans)
    corpus.append(ans)

In [ ]:
corpus = []
h = "Boston Globe denounces Trump candidacy in 'front page' satire "
words = h.lower()
words = re.sub('[^a-zA-Z]',' ',words)   
words = words.split()
ans = [stem.stem(word) for word in words if word not in stopwords.words('english')]
ans = ' '.join(ans)
corpus.append(ans)

['boston', 'globe', 'denounc', 'trump', 'candidaci', 'front', 'page', 'satir']

In [36]:
corpus

['boston globe denounc trump candidaci front page satir',
 'egypt detain peopl suspicion espionag turkey',
 'hous intellig committe trump lie obama absolut zero evid wiretap video',
 'buckey target normal oper bahama oil termin tuesday',
 'suspect boko haram suicid bomber kill least nigeria offici',
 'uk pm may promis uphold n ireland peac process brexit impass end',
 'watch stephen colbert moder hilari trump vs trump debat',
 'awesom gavin mcinn challeng trump protest epic result video',
 'wash hollywood loser make embarrass video bash trump pari climat agreement',
 'u auto safeti advocaci group name obama era offici top post',
 'priceless even think call storm victim comin back babi video',
 'consequ liber toler isi flag hang roof yet one report video',
 'watch jake tapper slam trump campaign manag tout fake assassin attempt',
 'paul ryan snap photo tell wrong imag',
 'gennif flower attend u presidenti debat penc',
 'sean spicer gave altern fact women march got obliter tweet',
 'futur democrat parti one pictur',
 'namibia dismiss u n expert claim north korea tie',
 'morawiecki sworn polish pm amid disput eu',
 'alec baldwin return snl blast trump humiliatingli terribl call world leader video',
 'obama urg congress give plan close guantanamo fair hear',
 'u protest march trump presid fifth day',
 'realiti show obama tell trump',
 'attent bad guy weapon sit duck colleg state',
 'episod sunday wire know drill guest robert singer jay dyer',
 'hilari leonardo dicaprio out climat chang hypocrit forc unimagin',
 'trump meet chicago mayor north carolina governor other',
 'trump say syrian christian refuge given prioriti',
 'michigan governor call congression hear flint water crisi',
 'young chines rebel feel pull famili tie',
 'jess jackson style shakedown naacp presid caught sell endors polit candid',
 'fbi tell trump go f ck fire director forc cancel visit',
 'venic commiss polish judiciari reform pose seriou risk',
 'fox host kennedi give jill stein ear want rememb video',
 'great pro coal oklahoma ag tap head epa',
 'hyster msnbc host get rapist confus call bill cosbi bill clinton video',
 'anti elit sloven presidenti candid seen run parliament narrow loss',
 'hous committe launch review fda crimin offic',
 'trump ban transgend servic member alarm militari offic',
 'suprem court give trump time file travel ban brief',
 'video rino strategist karl rove solut gun violenc repeal second amend',
 'sicken soro protest block u air forc vet enter inaugur ceremoni video',
 'pro eu group unveil soviet style mural trump kiss ex mayor johnson',
 'ador hispan trump fan interview dream meet mr trump video',
 'hear presid trump doubl condemn evil kkk white supremacist neo nazi video transcript',
 'twitter f ck trump say senat oppos muslim ban tri start world war iii tweet',
 'wapo report call liter hundr chariti search proof trump generos',
 'toilet paper social final stage venezuela byotp',
 'presid obama warn putin hack elect',
 'u hous vote republican dodd frank reform bill next week',
 'statu liberti muslim congressman spark protest hang paint offic',
 'watch michael steel call trump attack civil right icon rep john lewi',
 'hawaii grandma plea launch women march washington',
 'tale two donald trump give europ split headach',
 'turkish militari say begun reconnaiss syria idlib',
 'magnitud earthquak hit western iran state media',
 'michael jordan longer stay silent polic shoot take action',
 'obama cancel sleep plan stick around save democrat parti instead',
 'famili lost argentina submarin crew decri govern respons',
 'east london road block due signific polic incid',
 'wife arrest russian hacker spoke trump shake boot',
 'investor wilbur ross urg trump let behavior becom issu',
 'trump spokesman say possibl u embassi jerusalem stay tune',
 'megyn kelli unveil damn truth bomb trump amazingli hypocrit campaign perform',
 'japan oxford educ crown princ bring global view chrysanthemum throne',
 'minut use fake news stori destroy credibl popular conserv twitter person suggest hillari parkinson video',
 'trump popular slip rural america poll',
 'uk pm may revok articl eu exit process',
 'u penc german foreign minist agre nato central secur role white hous',
 'censor cranki berni call cnn fake news interview cnn cut mic video',
 'univ ga professor allow student choos grade help allevi stress',
 'judg napolitano bombshel intel tell trump inform one presid video',
 'mexico citi get unsteadili back feet quak',
 'histor obama work gay right memori right stop',
 'un physic remov independ media nyc hq expos institut corrupt',
 'controversi christian flag engulf small town',
 'uncl tom cnn guest attack larri wilmor someon call sander k word video',
 'trump travel ban show u misunderstand anti terror duti chines state media',
 'main democrat lawmak blast threaten post trump',
 'franc macron say euro zone need budget financ minist',
 'depart store chain drop ivanka trump like bad habit daddi f ck countri',
 'democrat chanc unless start',
 'u lawmak seek visa afghan help u forc',
 'simpson destroy idioci polit correct left colleg campus hilari video',
 'ammon bundi suddenli chang heart whole die freedom thing',
 'trump said media lie pathet inaugur crowd cnn respons perfect video',
 'eu question russia vote navalni decis',
 'perceiv snub uk may call trump strengthen tie',
 'indian journalist activist protest murder newspap publish',
 'duke hazard video eerili predict futur must watch',
 'list mayor us citi ask obama refuge',
 'women inform gop governor reproduct cycl statu protest anti abort law video',
 'itali former pm renzi lose alli elect near',
 'four u state sue interior depart coal leas public land',
 'clinton lead trump percent washington post abc poll',
 'stricter missouri abort rule take effect legal fight',
 'al gore perfect piec advic donald trump',
 'simpl graph blow media liber bia myth complet water imag',
 'kati hopkin warn american grave danger ahead let great countri becom unit kingdom video',
 'u judg order former trump aid stay home arrest',
 'trump say mexico eventu pay border wall',
 'senat wyden pledg fight limit encrypt',
 'uncertain afghanistan look trump decis troop aid',
 'kremlin say report trump disclos intellig nonsens',
 'hong kong leader demand end independ talk warn tie beij risk',
 'trump jump start search fbi chief two interview',
 'bravo ted cruz introduc bill help trump keep one biggest campaign promis american',
 'presid trump terribl found obama wire tap trump tower victori mccarthyism',
 'texa elector resign vote trump would bring dishonor god',
 'putin threaten releas top secret email hillari judg napolitano say bad news hillari video',
 'win u pull un organ israel follow video',
 'ever wonder peopl scream f ck donald trump sound like video',
 'vote trump help america export trash video',
 'watch peggi hubbard defend trump talk attack defend confeder statu antifa black live matter show weapon want fight',
 'tax buy billionair stadium charg hot dog obama say',
 'saudi man abdullah alhorir scald whip beat wife assault daughter hotel room trip disneyworld cop say',
 'u make lot progress north korea issu trump',
 'trump new christian polici advisor actual think control weather video',
 'trump stop infrastructur speech go rail democrat video',
 'obama dig research potenti suprem court pick',
 'big govern tyranni save ted cruz belov texa obama approv disast aid',
 'nsa architect nsa snoop expir fed continu surveil american phone record',
 'hyster msnbc host get rapist confus call bill cosbi bill clinton video',
 'comedi gold local tv news traffic report show crybabi hillari support easiest rout canada video',
 'libertarian parodi star war',
 'boom marin pen letter entitl racist mooch blame black peopl ignor come mouth',
 'saudi crown princ call iran suppli rocket militari aggress',
 'trump delay move u embassi jerusalem despit campaign pledg',
 'american care facebook ceo threaten user muslim refuge hate speech',
 'ireland readi let brexit talk move stage minist',
 'former presidenti rival jeb bush say vote trump',
 'break obama appoint judg demand rnc reveal trump plan prevent voter fraud',
 'hippi throwback video photo emerg socialist punk berni sander cuf arrest',
 'instead u midterm sander focus smaller race',
 'lol trump respond race obsess congressman lewi call illegitim presid media attack loathsom trump video',
 'republican never watch arrog jimmi kimmel said',
 'brazil temer escap corrupt charg committe vote',
 'uk hate crime surg brexit milit attack',
 'susan rice refus testifi senat believ reason',
 'number refuge welcom u sinc pari terror attack one christian muslim',
 'soda tax may spread voter check ballot california colorado',
 'gop megadonor sheldon adelson refus ted cruz visit piec sh',
 'iran nuclear deal fight threaten senat spend bill',
 'oop media think voter would forget hillari friend mentor late kkk leader robert byrd video',
 'trump fake poll number claim win clearli insan imag',
 'trump clinton isra fret either like alli',
 'russia call emerg u n task forc meet syria strike',
 'boiler room ep agenda beyond branko mali patrick henningsen mike robinson',
 'bill reilli made offens outrag claim black live matter ever',
 'ex catalonia leader turn belgian polic vrt',
 'turkish forc set posit syria idlib',
 'liber brilliantli troll gop petit make convent open carri event',
 'white supremacist trump alli get punch scream clinton rapist cri like babi video',
 'exclus trump support like view black neg reuter ipso poll',
 'trump tout urban polici follow detour open new hotel',
 'watch ted cruz claim democrat parti kkk get instantli own fact',
 'eu execut move punish poland court reform',
 'mnuchin see u growth reach percent time tax cut help',
 'death blasphem increas polit ralli cri pakistan',
 'marklevin freak awesom obama negoti iran iranian gener say israel destruct negoti',
 'finland suspect russian aircraft violat airspac',
 'amaz entranc trump le deplor video',
 'leftist actress alyssa milano get blast twitter call presid trump nation prayer day tx hurrican victim nation hole day',
 'norway receiv first f fighter jet',
 'wow bob beckel fox news host five hot water',
 'flashback hillari raunchi actress discuss desir see rock star peni look video',
 'japan arrest north korean crew amid mysteri boat arriv',
 'oregon cop convict shatter biker collarbon kick forgot dashcam video',
 'u republican group hit russian link viru research',
 'threat busi remov trump sign prompt even better pro trump display video',
 'darrel issa trump muslim ban ok happen peopl color daili video',
 'suspect london finsburi park mosqu attack plead guilti',
 'senat quicken pace approv trump judici pick',
 'intern observ watch u vote close',
 'washington post prais michel obama reclaim imag openli support racist cop hate black live matter',
 'turkey detain teacher suspect link coup dogan',
 'figur show trump spent million cash elect campaign',
 'uk counter terror polic arrest woman offici secret act',
 'berni sander hit back media brilliant way',
 'russia say u action toward consul state hooligan',
 'suprem court agre take obama un american plan shield million illeg deport',
 'watch john kerri fear monger iran deal support profound damag implic deni congress',
 'state prosecutor urg trump withdraw pari accord',
 'trump float ban defens firm hire militari procur offici',
 'key conserv u lawmak say make headway healthcar bill',
 'famili c shoot victim messag al sharpton gonna like',
 'danish govern win back budget defus crisi',
 'papua new guinean polic evict asylum seeker australian run camp unhcr decri forc use',
 'obama final month racist desper congression black caucu plan gun control antic hous floor disrupt possibl speaker ryan',
 'hooker hillari got back video',
 'break clinton clear coordin last minut trick energ hillari base',
 'u senat say cuba castro keen continu detent',
 'trump visit u suprem court justic weigh travel ban',
 'blood sport gop presidenti race take anoth brutal turn parti favorit tear trump',
 'saudi led coalit say strike hit legitim target yemen',
 'neil cavuto give huge realiti check colleg activist want free colleg video',
 'hand new video emerg show fbi shoot kill father oregon protest face',
 'gun dealer back sell zimmerman murder weapon close social media account',
 'church offer sanctuari protect illeg alien ahead dh raid',
 'trump econom advisori group clash populist imag',
 'somaliland pick rule parti candid new presid',
 'fugit former thai pm yingluck get five year jail absentia',
 'game changer trump bring back miss voter gop forgot',
 'coup coup zimbabw herald miss armi move mugab',
 'youtub give disgust reason pull ad revenu outspoken presid trump fan diamond silk video suitabl advertis',
 'mugab zimbabw liber mani oppressor',
 'fox legal expert call partial mueller must resign latest hire appoint obama video',
 'watch colbert found trump pro polic brutal cop stop talk',
 'far right want austria join group anti immigr state',
 'pulitz prize win author toni morrison want see cop shoot white unarm teenag back',
 'al cop goe ballist fellow offic record disput video',
 'trump say could jettison drug czar pick',
 'us senat major leader care implement immigr curb',
 'trump regret move sassi gay republican healthcar angst need right',
 'uk may pick brexit replac scandal hit aid minist',
 'u senat financ panel unlik support import tax chairman',
 'merkel open coalit talk fdp green also spd',
 'u halt new coal leas feder land first review decad',
 'defeat islam state raqqa may herald wider struggl u',
 'democrat demand probe trump health nomine',
 'swiss stop seiz incom asylum seeker pay upkeep',
 'obama continu win watchdog confirm iran compli treati',
 'respons gun owner blow leg turn lawnmow explod target',
 'mani nigerian displac boko haram fight readi return home',
 'pope land bangladesh meet rohingya group friday',
 'czech lawmak vote forc pm candid babi face fraud charg',
 'col oliv north five fact prove obama polici led rise isi video',
 'u tax avoid clampdown potenti headach appl',
 'chines envoy exchang view korean peninsula issu north korea',
 'middl east leader paint dark pictur rome confer',
 'catalonia formal declar independ spain suspend region autonomi sourc',
 'veryfakenew cnn underestim oppon new report show cnn take massiv nosed rate',
 'u north korea clash u n forum nuclear weapon',
 'lawyer shot kill wife blame black live matter video',
 'vehement anti gay pastor arrest count child porn',
 'driver ram german parti headquart appar suicid bid',
 'eu work deal scenario brexit',
 'terror expert sebastian gorka next london terror attack video',
 'explod african refuge popul stress welfar system minnesota send million dollar back africa',
 'potenti nuclear disast loom ny state nobodi news talk',
 'polic offic ask daughter school remov hate draw display school shock respons',
 'elect fraud happen michigan happen ohio',
 'behold donald trump th grader respons obama zero f ck left state union tweet',
 'sarah palin remov offens tweet humili whine black man donat chariti',
 'rnc shoot weak loser respons see million ad buy dump buzzfe',
 'maddow trump entir campaign one big money make scam video',
 'japan abe agre putin north korea nuclear test threaten peac',
 'controversi school brave student wear fake news shirt field trip cnn',
 'lt col toni shaffer muslim dnc staffer sent sensit info muslim brotherhood video',
 'rapist cop daniel holtzclaw disappear prison databas imag',
 'conserv gay guy blast penc aspen neighbor hang make america gay banner front hous',
 'japan inc want abe elect win smaller major',
 'russia say continu dialogu washington north korea iran ria',
 'hilari watch trump reaction bill clinton barack obama tough talk immigr video',
 'lockhe near billion helicopt deal pentagon',
 'vietnam brace typhoon khanun flood kill',
 'bid fix iran nuclear deal face uphil climb u congress',
 'tension rise australia start dismantl papua new guinea detent center',
 'china urg thailand find muslim uighur quickli dramat cell break',
 'white male broader bureaucraci mirror trump cabinet profil',
 'ep patrick henningsen live western land guest doyel shamley',
 'russia confirm putin trump talk joint cyber unit',
 'socialist millenni magnet berni sander tell support vote hillari caught say lie support free stuff',
 'watch colbert goe call new elect hilari must see monologu',
 'anti trump protest becom new ferguson illeg democrat video',
 'trump milit attack europ report',
 'wow former muslim messag refuge betray america goe viral muslim live benefit countri stand america',
 'exclus u envoy told coy engag pari climat deal cabl',
 'sarah palin get own suck julian assang call terrorist',
 'ann coulter get eaten aliv gop strategist wildli entertain video',
 'sheriff clark destroy idioci gun control democrat ghetto hell hole like blood soak chicago',
 'exclus state depart tell refuge agenc downsiz u oper',
 'trump name alt right racist chief strategist video',
 'trump russia revel rais hope u sanction bill',
 'trump advis bannon say u econom war china media',
 'democrat sander big fan pope attend vatican confer',
 'former democrat vote trump rip democrat done noth us noth promis video',
 'two republican senat join opposit revis healthcar bill',
 'trump tv event clinton say putin better leader obama',
 'lie lie lie fox shep smith break rank goe nuclear team trump video',
 'pressur trump like intens second debat clinton',
 'despit strain vietnam china forg closer econom tie',
 'democrat rise earli statehous win test new face',
 'three shock reason hillari clinton consid abort extremist',
 'obama threaten surfac leftist bunker speak trump plan end daca',
 'turkey releas german citizen sign thaw tie gabriel',
 'indonesian school launchpad child fighter syria islam state',
 'u fli bomber korea trump discuss option',
 'trump tweet refer prevent nuclear prolifer spokesman',
 'donald trump accident interview russian tv cours video',
 'thai govern take action monk anti muslim view',
 'video donald trump messag black live matter bulli',
 'trump pois lift feder coal ban green rule white hous',
 'donald trump jr tweet unintent humili photo block peopl mock',
 'hariri say hezbollah must remain neutral ensur lebanon move forward',
 'senat confirm new usaid administr mark green',
 'break wikileak releas vault part year zero',
 'colbert lay cathol smack trump pope franci fight video',
 'franc macron back spain constitut uniti call pm rajoy',
 'exclus mexican leftist point lead ahead elect poll',
 'mom whose children kill illeg testifi congress today',
 'tillerson north korea enemi us seek dialogu regim chang',
 'kansa governor order plan parenthood fund cut',
 'coalit merkel automat option open germani spd',
 'watch tucker carlson destroy leftist professor claim privileg teach futur dead cop defend antifa right beat oppon',
 'violenc convuls elect campaign test trump clinton',
 'eye bleach alert hillari get groov fellow looni dem video',
 'wow former ambassador russia list failur obama syria video',
 'black man claim kick swanki la gym support presid trump watch jess peterson tell incred stori',
 'never seen fbi trove pentagon photo refuel conspiraci suspicion',
 'duck man spoken duck dynasti patriarch announc choic presid great video',
 'philippin presid son deni link million drug shipment',
 'news graphic video michigan woman run rival car follow street brawl',
 'conserv shill tri tell van jone black men behav go well video',
 'white student accus drag black classmat rope around neck video',
 'trump call russia report fake news total polit witch hunt',
 'factbox trump twitter septemb tax reform florida clinton',
 'texa suprem court prove support marriag equal',
 'brazil largest ever corrupt probe near end judg say',
 'almost year later donald trump sound lot like theodor roosevelt immigr mean american video',
 'spain pass law make easier compani move around countri',